/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
    	SportCar sportCar = new SportCar() ;
    	sportCar.start() ;
    	sportCar.speedOn();
    	sportCar.sportCarStart();
    	
    	Truck truckCar = new Truck() ;
    	truckCar.start() ;
    	truckCar.payLoad();
    	truckCar.truckStart();
    	
    }
}
